name: python setup

on:
 workflow_dispatch
jobs:
 python-setup:
  runs-on: ubuntu-latest
  steps:
   - name: Setup Python
     uses: actions/setup-python@v5
     with:
      python-version: '3.13' 
   - name: Print python Version
     run:  python --version
